#AozoraEpub3 Parameters
#Fri Dec 19 07:36:56 GMT+09:00 2025
TocPage=1
CoverPage=1
TitlePage=2
TitlePageWrite=1
TitleToc=1
NcxNest=1
NavNest=1
ChapterExclude=1
ChapterSection=1
ChapterH=1
ChapterH1=1
ChapterH2=1
ChapterH3=1
ChapterName=1
MaxChapterNameLength=64
AutoYoko=1
AutoYokoNum1=1
AutoYokoNum3=1
PageBreakSize=400
PageBreakEmptySize=300
PageBreakChapterSize=200
SpaceHyphenation=1
DakutenType=2
